plugins {
    id 'java'
}

group = 'org.garlicrot'
version = '1.0.7'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.java-websocket:Java-WebSocket:1.5.4'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes(
                'Main-Class': 'garlicrot.rusherchatserver.ChatServer',
                'Implementation-Title': 'RusherChatServer',
                'Implementation-Version': project.version.toString()
        )
    }

    // Include all dependencies inside the JAR
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
