app = "rusherchatserver"
primary_region = "sea"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "42424"

[[services]]
internal_port = 42424
protocol = "tcp"
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]